server:
  addr: "http://127.0.0.1:8000"
  grpc: "grpc://localhost:8080"
  debug: true

postgresql:
  host: "0.0.0.0"
  port: "5432"
  dbname: "iot"
  user: "iot"
  password: "123456"
  sslmode: "disable"
  maxOpenConns: 100
  maxIdleConns: 10
  debug : false

redis:
  addr: "0.0.0.0:6379"
  password: ""
  db : 0

oss:
  endpoint: "oss-cn-.aliyuncs.com"
  accessKey: ""
  accessSecretKey: ""
  bucketName: "szyy-user"

email:
  user: "@qq.com"
  password: ""
  host: "smtp.qq.com:587"
  subject: "welcome use iot system, pleace active your email"
  codeExpire: 10*60*1000*1000
  activeUrl: "http://0.0.0.0/user/email"

jwt:
  secret: "secret"
