server:
  addr: "http://127.0.0.1:8000"
  grpc: "grpc://localhost:8080"
  debug: true

postgresql:
  host: "0.0.0.0"
  port: "5432"
  dbname: "iot"
  user: "iot"
  password: "123456"
  sslmode: "disable"
  maxOpenConns: 100
  maxIdleConns: 10
  debug : true

redis:
  addr: "0.0.0.0:6379"
  password: ""
  db : 0

oss:
  endpoint: "oss-cn-xxx.aliyuncs.com"
  accessKey: "aaa"
  accessSecretKey: "bbb"
  bucketName: "ccc-ddd"

email:
  user: "1@1.com"
  password: "eee"
  host: "smtp.fff.com:587"
  subject: "welcome use iot system, pleace active your email"

jwt:
  secret: "secret"